/* FOH Toolkit 3.0 — show builder + visual patch */
(function(){
  'use strict';
  const BOX={
    dx168:['DX168',16,8,'SLink','SLink'],ab168:['AB168',16,8,'dSnake','dSnake'],ar2412:['AR2412',24,12,'dSnake','dSnake'],gx4816:['GX4816',48,16,'SLink','SLink'],ar84:['AR84',8,4,'dSnake','dSnake'],dx164w:['DX164-W',16,4,'SLink','SLink'],dx88p:['DX88-P',8,8,'SLink','SLink'],dx012:['DX012',0,12,'SLink','SLink'],dx32:['DX32',0,0,'DX','DX',true],
    s16:['Behringer S16',16,8,'AES50-A Input','AES50-A Output'],sd16:['Behringer SD16',16,8,'AES50-A Input','AES50-A Output'],sd8:['Behringer SD8',8,8,'AES50-A Input','AES50-A Output'],s32:['Behringer S32',32,16,'AES50-A Input','AES50-A Output'],flow4vio:['FLOW 4VIO',4,0,'StageConnect Input','StageConnect Output'],dl8:['Midas DL8',8,8,'AES50-A Input','AES50-A Output'],dl16:['Midas DL16',16,8,'AES50-A Input','AES50-A Output'],dl32:['Midas DL32',32,16,'AES50-A Input','AES50-A Output'],dl151:['Midas DL151',24,0,'Stage I/O Input','Stage I/O Output'],dl152:['Midas DL152',0,24,'Stage I/O Input','Stage I/O Output'],dl153:['Midas DL153',16,8,'Stage I/O Input','Stage I/O Output'],dl154:['Midas DL154',8,16,'Stage I/O Input','Stage I/O Output'],dl155:['Midas DL155',16,16,'Stage I/O Input','Stage I/O Output'],dl231:['Midas DL231',24,24,'Stage I/O Input','Stage I/O Output'],dl251:['Midas DL251',48,16,'Stage I/O Input','Stage I/O Output'],dl252:['Midas DL252',16,48,'Stage I/O Input','Stage I/O Output'],dl451:['Midas DL451',0,0,'Stage I/O Input','Stage I/O Output',true],
    tio1608d:['Yamaha Tio1608-D',16,8,'Dante Input','Dante Output'],tio1608d2:['Yamaha Tio1608-D2',16,8,'Dante Input','Dante Output'],rio1608d:['Yamaha Rio1608-D',16,8,'Dante Input','Dante Output'],rio3224d:['Yamaha Rio3224-D',32,16,'Dante Input','Dante Output'],rio1608d2:['Yamaha Rio1608-D2',16,8,'Dante Input','Dante Output'],rio3224d2:['Yamaha Rio3224-D2',32,16,'Dante Input','Dante Output'],rio1608d3:['Yamaha Rio1608-D3',16,8,'Dante Input','Dante Output'],rio3224d3:['Yamaha Rio3224-D3',32,16,'Dante Input','Dante Output'],rpio622:['Yamaha RPio622',0,0,'TWINLANe Input','TWINLANe Output',true],rpio222:['Yamaha RPio222',0,0,'TWINLANe Input','TWINLANe Output',true],
    sc16i:['Mini Stagebox 16i',16,8,'MADI Input','MADI Output'],sc32i:['Mini Stagebox 32i',32,12,'MADI Input','MADI Output'],sc16r:['Mini Stagebox 16R',16,8,'MADI Input','MADI Output'],sc32r:['Mini Stagebox 32R',32,8,'MADI Input','MADI Output'],sccompact:['Compact Stagebox',0,0,'MADI Input','MADI Output',true],scvistage:['Vi Stagebox 64/32',64,32,'MADI Input','MADI Output'],
    drack96:['DiGiCo D-Rack 96 kHz',28,8,'Rack Input','Rack Output'],drack48:['DiGiCo D-Rack 48 kHz',32,8,'Rack Input','Rack Output'],d2rack:['DiGiCo D2-Rack',48,16,'Rack Input','Rack Output'],mqrack:['DiGiCo MQ-Rack',48,24,'Rack Input','Rack Output'],dqrack:['DiGiCo DQ-Rack',48,24,'Rack Input','Rack Output'],sdrack:['DiGiCo SD-Rack',0,0,'Rack Input','Rack Output',true],sdmini:['DiGiCo SD-MiNi',0,0,'Rack Input','Rack Output',true],sdnano:['DiGiCo SD-Nano',0,0,'Rack Input','Rack Output',true],a168stage:['DiGiCo A168 STAGE',16,8,'A3232 Input','A3232 Output'],
    avidstage48:['Avid Stage 48',48,24,'Stage Input','Stage Output'],avidstage16:['Avid Stage 16',16,8,'Stage Input','Stage Output'],avidstage32:['Avid Stage 32',0,0,'Stage Input','Stage Output',true],avidstage64:['Avid Stage 64',0,0,'Stage Input','Stage Output',true],
    nsb168:['PreSonus NSB 16.8',16,8,'AVB Input','AVB Output'],nsb88:['PreSonus NSB 8.8',8,8,'AVB Input','AVB Output'],sslsb3224:['SSL SB 32.24',32,16,'Dante Input','Dante Output'],sslsb1612:['SSL SB 16.12',16,8,'Dante Input','Dante Output'],sslsb88:['SSL SB 8.8',8,8,'Dante Input','Dante Output'],sslsbi16:['SSL SBi16',16,0,'Dante Input','Dante Output'],tascamsb16d:['TASCAM SB-16D',16,16,'Dante Input','Dante Output'],rolands2416:['Roland S-2416',24,16,'REAC A Input','REAC A Output'],rolands1608:['Roland S-1608',16,8,'REAC A Input','REAC A Output'],rolands0816:['Roland S-0816',8,16,'REAC A Input','REAC A Output']
  };
  const LOCAL={ah_sq5:['SQ-5 local I/O',16,12,'Local XLR','Local XLR'],ah_sq6:['SQ-6 local I/O',24,14,'Local XLR','Local XLR'],ah_sq7:['SQ-7 local I/O',32,16,'Local XLR','Local XLR'],ah_sqrack:['SQ-Rack local I/O',16,12,'Local XLR','Local XLR'],ah_sq5plus:['SQ5+ local I/O',16,12,'Local XLR','Local XLR'],ah_sq6plus:['SQ6+ local I/O',24,14,'Local XLR','Local XLR'],ah_sq7plus:['SQ7+ local I/O',32,16,'Local XLR','Local XLR'],yam_dm3:['DM3 local I/O',16,8,'Local Input','Local Output'],yam_dm3s:['DM3 Standard local I/O',16,8,'Local Input','Local Output'],yam_dm7:['DM7 local I/O',32,16,'Local Input','Local Output'],yam_dm7c:['DM7 Compact local I/O',16,16,'Local Input','Local Output']};
  let activeShowId=null,activeTab='overview',pickerShowId=null;

  function normalKey(k){return typeof normaliseConsoleKey==='function'?normaliseConsoleKey(k):k;}
  function hw(show){
    if(show.stageboxProfile==='local'){const x=LOCAL[normalKey(show.console)];return x?{id:'local',name:x[0],inputs:x[1],outputs:x[2],inPrefix:x[3],outPrefix:x[4],manual:false}:null;}
    const x=BOX[show.stageboxProfile];return x?{id:show.stageboxProfile,name:x[0],inputs:x[1],outputs:x[2],inPrefix:x[3],outPrefix:x[4],manual:!!x[5]}:null;
  }
  function ensure(show){show.channels=Array.isArray(show.channels)?show.channels:[];show.io=show.io&&typeof show.io==='object'?show.io:{};show.outputs=Array.isArray(show.outputs)?show.outputs:[];show.softKeys=Array.isArray(show.softKeys)?show.softKeys:[];show.dcas=Array.isArray(show.dcas)?show.dcas:[];show.muteGroups=Array.isArray(show.muteGroups)?show.muteGroups:[];show.notes=show.notes||'';show.stageboxProfile=show.stageboxProfile||'manual';}
  function save(){persist();renderShows();}
  function channelPreset(ch){return presets.find(p=>p.id===ch.presetId)||null;}
  function trailingNumber(text){const m=String(text||'').match(/(\d+)\s*$/);return m?Number(m[1]):null;}
  function usedInputs(show){const set=new Set();show.channels.forEach(c=>{const n=trailingNumber(show.io[c.id]?.source);if(n)set.add(n);});return set;}
  function nextInput(show){const h=hw(show);if(!h||h.manual||!h.inputs)return null;const used=usedInputs(show);for(let i=1;i<=h.inputs;i++)if(!used.has(i))return i;return null;}
  function addPreset(show,p){const ch={id:crypto.randomUUID(),presetId:p.id,name:p.name};show.channels.push(ch);const n=nextInput(show);const h=hw(show);show.io[ch.id]={source:n&&h?`${h.inPrefix} ${n}`:'',channel:`Input CH ${show.channels.length}`,customSource:''};save();return ch;}
  function addBlank(show){const ch={id:crypto.randomUUID(),presetId:null,name:`Custom Channel ${show.channels.length+1}`,custom:true};show.channels.push(ch);const n=nextInput(show);const h=hw(show);show.io[ch.id]={source:n&&h?`${h.inPrefix} ${n}`:'',channel:`Input CH ${show.channels.length}`,customSource:''};save();return ch;}
  function cloneShow(show){const copy=structuredClone?structuredClone(show):JSON.parse(JSON.stringify(show));copy.id=crypto.randomUUID();copy.name=`${show.name} Copy`;copy.channels.forEach(c=>{const old=c.id;c.id=crypto.randomUUID();const oldIo=copy.io[old];delete copy.io[old];copy.io[c.id]=oldIo||{};copy.dcas.forEach(g=>g.members=(g.members||[]).map(x=>x===old?c.id:x));copy.muteGroups.forEach(g=>g.members=(g.members||[]).map(x=>x===old?c.id:x));});state.shows.push(copy);save();toast('Show duplicated');return copy;}

  function presetOptions(selected){return `<option value="">Custom / no preset</option>${presets.map(p=>`<option value="${esc(p.id)}" ${p.id===selected?'selected':''}>${esc(p.name)}</option>`).join('')}`;}
  function header(show){const d=typeof getDeskProfile==='function'?getDeskProfile(show.console):{name:show.console};const h=hw(show);return `<div class="detail-head"><span class="eyebrow">MY SHOW · WORKSPACE</span><h2>${esc(show.name)}</h2><p>${show.channels.length} channels · ${esc(d.name)}${h?` · ${esc(h.name)}`:''}</p></div><div class="show-desk-select"><label>SHOW DESK</label><select id="showConsoleSelect">${typeof consoleOptionsHTML==='function'?consoleOptionsHTML(show.console):''}</select></div>`;}
  function tabs(){return `<div class="segment show-segment v3-show-tabs"><button data-v3-show-tab="overview">Overview</button><button data-v3-show-tab="channels">Channels</button><button data-v3-show-tab="patch">Patch</button><button data-v3-show-tab="groups">Groups & Keys</button><button data-v3-show-tab="notes">Notes</button><button data-v3-show-tab="export">Export</button></div>`;}

  function overviewPane(show){const h=hw(show);const unassigned=show.channels.filter(c=>!show.io[c.id]?.source).length;return `<div class="v3-show-pane" data-v3-pane="overview"><div class="v3-stat-grid"><div><span>Channels</span><strong>${show.channels.length}</strong></div><div><span>Unpatched</span><strong>${unassigned}</strong></div><div><span>DCAs</span><strong>${show.dcas.length}</strong></div><div><span>Mute groups</span><strong>${show.muteGroups.length}</strong></div></div><div class="panel v3-workflow-card"><span class="eyebrow">QUICK ACTIONS</span><div class="v3-action-grid"><button class="primary" id="v3BrowsePresets">＋ Add presets</button><button class="secondary" id="v3AddBlank">＋ Blank channel</button><button class="secondary" id="v3DuplicateShow">Duplicate show</button><button class="secondary" data-v3-jump="patch">Open patch</button></div></div><div class="panel v3-workflow-card"><span class="eyebrow">I/O HARDWARE</span><h3>${esc(h?.name||'Manual / custom I/O')}</h3><p>${h?.manual?'Modular/configuration-dependent hardware. Socket patching stays manual.':h?`${h.inputs} inputs · ${h.outputs} outputs`:'No fixed-I/O hardware selected.'}</p></div></div>`;}

  function channelRows(show){return show.channels.length?show.channels.map((c,i)=>{const p=channelPreset(c);return `<div class="v3-channel-manage" draggable="true" data-v3-channel="${esc(c.id)}"><div class="v3-drag">☰</div><div class="v3-channel-num">${i+1}</div><div class="v3-channel-fields"><input data-v3-ch-name="${esc(c.id)}" value="${esc(c.name)}" aria-label="Channel ${i+1} name"><select data-v3-ch-preset="${esc(c.id)}">${presetOptions(c.presetId)}</select><small>${esc(show.io[c.id]?.source||'Unpatched')} · ${esc(p?.style||'Custom channel')}</small></div><div class="v3-channel-buttons"><button class="mini-btn" data-v3-up="${esc(c.id)}" ${i===0?'disabled':''}>↑</button><button class="mini-btn" data-v3-down="${esc(c.id)}" ${i===show.channels.length-1?'disabled':''}>↓</button><button class="mini-btn" data-v3-dup="${esc(c.id)}">Copy</button><button class="mini-btn danger-mini" data-v3-remove="${esc(c.id)}">×</button></div></div>`;}).join(''):'<div class="empty-state">No channels yet.</div>';}
  function channelsPane(show){return `<div class="v3-show-pane" data-v3-pane="channels"><div class="v3-pane-head"><div><span class="eyebrow">CHANNEL LIST</span><h3>Build the show</h3></div><div class="button-row"><button class="primary" id="v3BrowsePresets2">＋ Preset</button><button class="secondary" id="v3AddBlank2">＋ Blank</button></div></div><p class="helper">Drag rows on desktop or use ↑/↓ on mobile. Renaming a channel does not change its source patch.</p><div id="v3ChannelRows">${channelRows(show)}</div></div>`;}

  function inputGrid(show,h){if(!h||h.manual||!h.inputs)return `<div class="empty-state">Visual socket layout is available for fixed-I/O hardware. This show is using ${esc(h?.name||'manual I/O')}.</div>`;const byN=new Map();show.channels.forEach(c=>{const n=trailingNumber(show.io[c.id]?.source);if(n)byN.set(n,c);});return `<div class="v3-socket-grid">${Array.from({length:h.inputs},(_,i)=>{const n=i+1,c=byN.get(n);return `<div class="v3-socket ${c?'used':'free'}"><span>${n}</span><strong>${c?esc(c.name):'FREE'}</strong></div>`;}).join('')}</div>`;}
  function outputGrid(show,h){if(!h||h.manual||!h.outputs)return '';const byN=new Map();(show.outputs||[]).forEach(o=>{const n=trailingNumber(o.dest);if(n)byN.set(n,o);});return `<div class="v3-socket-grid outputs">${Array.from({length:h.outputs},(_,i)=>{const n=i+1,o=byN.get(n);return `<div class="v3-socket ${o?'used':'free'}"><span>${n}</span><strong>${o?esc(o.source||o.name||'OUT'):'FREE'}</strong></div>`;}).join('')}</div>`;}
  function inputPatchRows(show,h){return show.channels.map((c,i)=>{const io=show.io[c.id]||{};if(h&&!h.manual&&h.inputs){const cur=trailingNumber(io.source)||'';return `<div class="v3-patch-row"><span>${i+1}</span><strong>${esc(c.name)}</strong><select data-v3-input-socket="${esc(c.id)}"><option value="">Unassigned</option>${Array.from({length:h.inputs},(_,j)=>`<option value="${j+1}" ${cur===j+1?'selected':''}>${esc(h.inPrefix)} ${j+1}</option>`).join('')}</select></div>`;}return `<div class="v3-patch-row"><span>${i+1}</span><strong>${esc(c.name)}</strong><input data-v3-input-manual="${esc(c.id)}" value="${esc(io.source||'')}" placeholder="Input source / socket"></div>`;}).join('');}
  function outputRows(show){return (show.outputs||[]).map((o,i)=>`<div class="v3-output-row"><input data-v3-out-source="${i}" value="${esc(o.source||o.name||'')}" placeholder="Source e.g. Main L"><input data-v3-out-dest="${i}" value="${esc(o.dest||'')}" placeholder="Physical output"><button class="mini-btn danger-mini" data-v3-out-remove="${i}">×</button></div>`).join('')||'<div class="empty-state compact-empty">No outputs programmed.</div>';}
  function patchPane(show){const h=hw(show);return `<div class="v3-show-pane" data-v3-pane="patch"><div class="v3-pane-head"><div><span class="eyebrow">VISUAL PATCH</span><h3>${esc(h?.name||'Manual I/O')}</h3></div><span class="count-pill">${h&&!h.manual?`${h.inputs} IN · ${h.outputs} OUT`:'MANUAL'}</span></div><div class="panel v3-workflow-card"><h4>Inputs</h4>${inputGrid(show,h)}<div class="v3-patch-list">${inputPatchRows(show,h)}</div></div><div class="panel v3-workflow-card"><div class="section-mini-head"><div><h4>Outputs</h4></div><button class="text-button" id="v3AddOutput">＋ Add</button></div>${outputGrid(show,h)}<div id="v3OutputRows">${outputRows(show)}</div></div></div>`;}

  function groupCard(show,g,type){return `<div class="panel v3-group-card" data-v3-group-card="${esc(g.id)}"><div class="section-mini-head"><input data-v3-group-name="${esc(type)}:${esc(g.id)}" value="${esc(g.name)}"><button class="mini-btn danger-mini" data-v3-group-remove="${esc(type)}:${esc(g.id)}">Remove</button></div><div class="v3-member-grid">${show.channels.map(c=>`<label><input type="checkbox" data-v3-member="${esc(type)}:${esc(g.id)}:${esc(c.id)}" ${(g.members||[]).includes(c.id)?'checked':''}><span>${esc(c.name)}</span></label>`).join('')||'<span class="helper">Add channels first.</span>'}</div></div>`;}
  function keyRows(show){return show.softKeys.map((k,i)=>`<div class="v3-output-row"><input data-v3-key-label="${i}" value="${esc(k.key||'')}" placeholder="Key / Macro"><input data-v3-key-action="${i}" value="${esc(k.action||'')}" placeholder="Function"><input data-v3-key-target="${i}" value="${esc(k.target||'')}" placeholder="Target"><button class="mini-btn danger-mini" data-v3-key-remove="${i}">×</button></div>`).join('')||'<div class="empty-state compact-empty">No assignable controls programmed.</div>';}
  function groupsPane(show){return `<div class="v3-show-pane" data-v3-pane="groups"><div class="v3-pane-head"><div><span class="eyebrow">CONTROL</span><h3>DCAs / VCAs</h3></div><button class="secondary" id="v3AddDca">＋ DCA/VCA</button></div>${show.dcas.map(g=>groupCard(show,g,'dca')).join('')||'<div class="empty-state">No DCA/VCA groups yet.</div>'}<div class="v3-pane-head"><div><span class="eyebrow">CONTROL</span><h3>Mute groups</h3></div><button class="secondary" id="v3AddMute">＋ Mute group</button></div>${show.muteGroups.map(g=>groupCard(show,g,'mute')).join('')||'<div class="empty-state">No mute groups yet.</div>'}<div class="panel v3-workflow-card"><div class="section-mini-head"><div><span class="eyebrow">DESK CONTROLS</span><h3>SoftKeys / macros</h3></div><button class="text-button" id="v3AddKey">＋ Add</button></div>${keyRows(show)}</div></div>`;}
  function notesPane(show){return `<div class="v3-show-pane" data-v3-pane="notes"><div class="panel v3-workflow-card"><span class="eyebrow">SHOW NOTES</span><h3>Anything you need at the gig</h3><textarea id="v3ShowNotes" rows="14" placeholder="Venue notes, PA notes, changeovers, monitor requests, microphone swaps, problem frequencies…">${esc(show.notes||'')}</textarea><p class="helper">Notes save automatically with the show and sync with your account.</p></div></div>`;}
  function exportPane(show){return `<div class="v3-show-pane" data-v3-pane="export"><div class="panel export-panel"><span class="eyebrow">BACKUP / EXPORT</span><h3>FOH Toolkit show package</h3><p>Export the complete channel list, patch, groups, notes and desk plan. Native console export is only shown where a format has been validated.</p><button class="primary full" id="exportShowBtn">Export .fohshow.json</button></div></div>`;}

  function renderShow(show){ensure(show);const detail=document.getElementById('showDetail');if(!detail)return;detail.innerHTML=`${header(show)}${tabs()}${overviewPane(show)}${channelsPane(show)}${patchPane(show)}${groupsPane(show)}${notesPane(show)}${exportPane(show)}<div class="button-row v3-show-bottom"><button class="secondary" id="renameShow">Rename</button><button class="danger-button" id="deleteShow">Delete show</button></div>`;bind(show);activate(activeTab);window.fohSqNative?.setActiveShow?.(show.id);}
  function activate(tab){activeTab=tab||'overview';document.querySelectorAll('[data-v3-show-tab]').forEach(b=>b.classList.toggle('active',b.dataset.v3ShowTab===activeTab));document.querySelectorAll('[data-v3-pane]').forEach(p=>p.classList.toggle('active',p.dataset.v3Pane===activeTab));}
  function rerender(show,tab=activeTab){renderShow(show);activate(tab);}

  function moveChannel(show,id,delta){const i=show.channels.findIndex(c=>c.id===id),j=i+delta;if(i<0||j<0||j>=show.channels.length)return;[show.channels[i],show.channels[j]]=[show.channels[j],show.channels[i]];show.channels.forEach((c,n)=>{show.io[c.id]=show.io[c.id]||{};show.io[c.id].channel=`Input CH ${n+1}`;});save();rerender(show,'channels');}
  function duplicateChannel(show,id){const src=show.channels.find(c=>c.id===id);if(!src)return;const ch={...src,id:crypto.randomUUID(),name:`${src.name} Copy`};show.channels.splice(show.channels.indexOf(src)+1,0,ch);const n=nextInput(show),h=hw(show);show.io[ch.id]={...(show.io[src.id]||{}),source:n&&h?`${h.inPrefix} ${n}`:'',channel:`Input CH ${show.channels.indexOf(ch)+1}`};save();rerender(show,'channels');}
  function removeChannel(show,id){show.channels=show.channels.filter(c=>c.id!==id);delete show.io[id];[...show.dcas,...show.muteGroups].forEach(g=>g.members=(g.members||[]).filter(x=>x!==id));save();rerender(show,'channels');}

  function bind(show){
    document.querySelectorAll('[data-v3-show-tab]').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.v3ShowTab)));
    document.querySelectorAll('[data-v3-jump]').forEach(b=>b.addEventListener('click',()=>activate(b.dataset.v3Jump)));
    document.getElementById('showConsoleSelect')?.addEventListener('change',e=>{show.console=normalKey(e.target.value);save();rerender(show,activeTab);toast(`Show desk: ${getDeskProfile(show.console).name}`);});
    document.getElementById('v3BrowsePresets')?.addEventListener('click',()=>openPicker(show.id));document.getElementById('v3BrowsePresets2')?.addEventListener('click',()=>openPicker(show.id));
    document.getElementById('v3AddBlank')?.addEventListener('click',()=>{addBlank(show);rerender(show,'channels');});document.getElementById('v3AddBlank2')?.addEventListener('click',()=>{addBlank(show);rerender(show,'channels');});
    document.getElementById('v3DuplicateShow')?.addEventListener('click',()=>{const c=cloneShow(show);document.getElementById('showDialog')?.close();setTimeout(()=>openShow(c.id),0);});
    document.querySelectorAll('[data-v3-ch-name]').forEach(i=>i.addEventListener('change',()=>{const c=show.channels.find(x=>x.id===i.dataset.v3ChName);if(c){c.name=i.value.trim()||c.name;save();rerender(show,'channels');}}));
    document.querySelectorAll('[data-v3-ch-preset]').forEach(s=>s.addEventListener('change',()=>{const c=show.channels.find(x=>x.id===s.dataset.v3ChPreset);if(!c)return;c.presetId=s.value||null;const p=channelPreset(c);if(p)c.name=p.name;save();rerender(show,'channels');}));
    document.querySelectorAll('[data-v3-up]').forEach(b=>b.addEventListener('click',()=>moveChannel(show,b.dataset.v3Up,-1)));document.querySelectorAll('[data-v3-down]').forEach(b=>b.addEventListener('click',()=>moveChannel(show,b.dataset.v3Down,1)));document.querySelectorAll('[data-v3-dup]').forEach(b=>b.addEventListener('click',()=>duplicateChannel(show,b.dataset.v3Dup)));document.querySelectorAll('[data-v3-remove]').forEach(b=>b.addEventListener('click',()=>removeChannel(show,b.dataset.v3Remove)));
    let dragged=null;document.querySelectorAll('[data-v3-channel]').forEach(row=>{row.addEventListener('dragstart',()=>dragged=row.dataset.v3Channel);row.addEventListener('dragover',e=>e.preventDefault());row.addEventListener('drop',e=>{e.preventDefault();const target=row.dataset.v3Channel;if(!dragged||dragged===target)return;const a=show.channels.findIndex(c=>c.id===dragged),b=show.channels.findIndex(c=>c.id===target);const [x]=show.channels.splice(a,1);show.channels.splice(b,0,x);save();rerender(show,'channels');});});
    document.querySelectorAll('[data-v3-input-socket]').forEach(s=>s.addEventListener('change',()=>{const h=hw(show),c=show.channels.find(x=>x.id===s.dataset.v3InputSocket);if(!c)return;show.io[c.id]=show.io[c.id]||{};show.io[c.id].source=s.value&&h?`${h.inPrefix} ${s.value}`:'';save();rerender(show,'patch');}));
    document.querySelectorAll('[data-v3-input-manual]').forEach(i=>i.addEventListener('change',()=>{show.io[i.dataset.v3InputManual]=show.io[i.dataset.v3InputManual]||{};show.io[i.dataset.v3InputManual].source=i.value.trim();save();rerender(show,'patch');}));
    document.getElementById('v3AddOutput')?.addEventListener('click',()=>{show.outputs.push({source:'',dest:''});save();rerender(show,'patch');});
    document.querySelectorAll('[data-v3-out-source]').forEach(i=>i.addEventListener('change',()=>{const o=show.outputs[Number(i.dataset.v3OutSource)];if(o){o.source=i.value.trim();o.name=o.source;save();}}));document.querySelectorAll('[data-v3-out-dest]').forEach(i=>i.addEventListener('change',()=>{const o=show.outputs[Number(i.dataset.v3OutDest)];if(o){o.dest=i.value.trim();save();rerender(show,'patch');}}));document.querySelectorAll('[data-v3-out-remove]').forEach(b=>b.addEventListener('click',()=>{show.outputs.splice(Number(b.dataset.v3OutRemove),1);save();rerender(show,'patch');}));
    document.getElementById('v3AddDca')?.addEventListener('click',()=>{show.dcas.push({id:crypto.randomUUID(),name:`DCA ${show.dcas.length+1}`,members:[]});save();rerender(show,'groups');});document.getElementById('v3AddMute')?.addEventListener('click',()=>{show.muteGroups.push({id:crypto.randomUUID(),name:`Mute Group ${show.muteGroups.length+1}`,members:[]});save();rerender(show,'groups');});
    document.querySelectorAll('[data-v3-group-name]').forEach(i=>i.addEventListener('change',()=>{const [type,id]=i.dataset.v3GroupName.split(':');const arr=type==='dca'?show.dcas:show.muteGroups;const g=arr.find(x=>x.id===id);if(g){g.name=i.value.trim()||g.name;save();}}));document.querySelectorAll('[data-v3-group-remove]').forEach(b=>b.addEventListener('click',()=>{const [type,id]=b.dataset.v3GroupRemove.split(':');if(type==='dca')show.dcas=show.dcas.filter(x=>x.id!==id);else show.muteGroups=show.muteGroups.filter(x=>x.id!==id);save();rerender(show,'groups');}));
    document.querySelectorAll('[data-v3-member]').forEach(i=>i.addEventListener('change',()=>{const [type,gid,cid]=i.dataset.v3Member.split(':');const arr=type==='dca'?show.dcas:show.muteGroups,g=arr.find(x=>x.id===gid);if(!g)return;const set=new Set(g.members||[]);i.checked?set.add(cid):set.delete(cid);g.members=[...set];save();}));
    document.getElementById('v3AddKey')?.addEventListener('click',()=>{show.softKeys.push({key:'',action:'',target:''});save();rerender(show,'groups');});document.querySelectorAll('[data-v3-key-label]').forEach(i=>i.addEventListener('change',()=>{show.softKeys[Number(i.dataset.v3KeyLabel)].key=i.value.trim();save();}));document.querySelectorAll('[data-v3-key-action]').forEach(i=>i.addEventListener('change',()=>{show.softKeys[Number(i.dataset.v3KeyAction)].action=i.value.trim();save();}));document.querySelectorAll('[data-v3-key-target]').forEach(i=>i.addEventListener('change',()=>{show.softKeys[Number(i.dataset.v3KeyTarget)].target=i.value.trim();save();}));document.querySelectorAll('[data-v3-key-remove]').forEach(b=>b.addEventListener('click',()=>{show.softKeys.splice(Number(b.dataset.v3KeyRemove),1);save();rerender(show,'groups');}));
    let noteT;document.getElementById('v3ShowNotes')?.addEventListener('input',e=>{show.notes=e.target.value;clearTimeout(noteT);noteT=setTimeout(save,350);});
    document.getElementById('exportShowBtn')?.addEventListener('click',()=>{if(typeof exportShowPackage==='function')exportShowPackage(show);});
    document.getElementById('renameShow')?.addEventListener('click',()=>{const n=prompt('Show name',show.name);if(n?.trim()){show.name=n.trim();save();rerender(show,activeTab);}});document.getElementById('deleteShow')?.addEventListener('click',()=>{if(confirm(`Delete ${show.name}?`)){state.shows=state.shows.filter(x=>x.id!==show.id);save();document.getElementById('showDialog')?.close();}});
  }

  function ensurePicker(){
    let d=document.getElementById('v3PresetPicker');if(d)return d;d=document.createElement('dialog');d.id='v3PresetPicker';d.className='sheet-dialog v3-picker';d.innerHTML=`<div class="sheet-handle"></div><div class="dialog-heading"><span class="eyebrow">SHOW BUILDER</span><h2>Add channels</h2></div><label class="search-box"><span>⌕</span><input id="v3PickerSearch" type="search" placeholder="Search presets…"></label><div id="v3PickerList" class="list-stack"></div><button class="icon-button close-sheet" id="v3PickerClose" aria-label="Close">×</button>`;document.body.appendChild(d);d.querySelector('#v3PickerClose').addEventListener('click',()=>d.close());d.querySelector('#v3PickerSearch').addEventListener('input',renderPicker);return d;
  }
  function openPicker(showId){pickerShowId=showId;const d=ensurePicker();d.querySelector('#v3PickerSearch').value='';renderPicker();if(!d.open)d.showModal();}
  function renderPicker(){const d=ensurePicker(),q=(d.querySelector('#v3PickerSearch').value||'').toLowerCase();const list=presets.filter(p=>!q||`${p.name} ${p.category} ${p.style}`.toLowerCase().includes(q));d.querySelector('#v3PickerList').innerHTML=list.map(p=>`<button class="list-item v3-picker-row" data-v3-pick="${esc(p.id)}"><div class="freq-chip">${esc(p.icon||'P')}</div><div class="grow"><h4>${esc(p.name)}</h4><p>${esc(p.category)} · ${esc(p.style)}</p></div><span>＋</span></button>`).join('');d.querySelectorAll('[data-v3-pick]').forEach(b=>b.addEventListener('click',()=>{const show=state.shows.find(s=>s.id===pickerShowId),p=presets.find(x=>x.id===b.dataset.v3Pick);if(show&&p){addPreset(show,p);toast(`${p.name} added`);renderPicker();if(activeShowId===show.id)rerender(show,'channels');}}));}

  window.openShow=function(id){const show=state.shows.find(s=>s.id===id);if(!show)return;activeShowId=id;activeTab='overview';ensure(show);renderShow(show);const d=document.getElementById('showDialog');if(d&&!d.open)d.showModal();};

  function ready(){state.shows.forEach(ensure);persist();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(ready,0));else setTimeout(ready,0);
})();
